#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Dec 15 20:24:41 UTC 2022
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 35a19cd2581b43a3a5bb87d4dac057fc --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot upcounter_testbench_behav xil_defaultlib.upcounter_testbench xil_defaultlib.glbl -log elaborate.log"
xelab -wto 35a19cd2581b43a3a5bb87d4dac057fc --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot upcounter_testbench_behav xil_defaultlib.upcounter_testbench xil_defaultlib.glbl -log elaborate.log

