# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/asheshpangma/VSD-FPGA-Fabric-Design-and-Architecture/Day4/post_synthesis_SOFA_counter/post_synth_sofa_counter/post_synth_sofa_counter.cache/wt [current_project]
set_property parent.project_path /home/asheshpangma/VSD-FPGA-Fabric-Design-and-Architecture/Day4/post_synthesis_SOFA_counter/post_synth_sofa_counter/post_synth_sofa_counter.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/asheshpangma/VSD-FPGA-Fabric-Design-and-Architecture/Day4/post_synthesis_SOFA_counter/post_synth_sofa_counter/post_synth_sofa_counter.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/asheshpangma/VSD-FPGA-Fabric-Design-and-Architecture/Day4/post_synthesis_SOFA_counter/post_synth_sofa_counter/post_synth_sofa_counter.srcs/sources_1/imports/post_synthesis_SOFA_counter/primitives.v
  /home/asheshpangma/VSD-FPGA-Fabric-Design-and-Architecture/Day4/post_synthesis_SOFA_counter/post_synth_sofa_counter/post_synth_sofa_counter.srcs/sources_1/imports/post_synthesis_SOFA_counter/up_counter_post_synthesis.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/asheshpangma/VSD-FPGA-Fabric-Design-and-Architecture/Day4/post_synthesis_SOFA_counter/post_synth_sofa_counter/post_synth_sofa_counter.srcs/constrs_1/imports/vtr_flow/counter.sdc
set_property used_in_implementation false [get_files /home/asheshpangma/VSD-FPGA-Fabric-Design-and-Architecture/Day4/post_synthesis_SOFA_counter/post_synth_sofa_counter/post_synth_sofa_counter.srcs/constrs_1/imports/vtr_flow/counter.sdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top up_counter -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef up_counter.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file up_counter_utilization_synth.rpt -pb up_counter_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
